/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PopBox: typeof import('./src/components/Pop-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemTechnologyEarth: typeof import('./src/components/3060220009/SystemTechnologyEarth/SystemTechnologyEarth.vue')['default']
  }
}
